Please input the city: {u'count': 1553.0,
 u'values': [{u'creator': u'/user/kake',
              u'id': u'/m/0nb9x',
              u'lang': u'en',
              u'text': u'Royal Borough of Kensington and Chelsea',
              u'timestamp': u'2007-08-09T16:38:32.000Z'},
             {u'creator': u'/user/awfrank',
              u'id': u'/m/01d_0p',
              u'lang': u'en',
              u'text': u'Hyde Park',
              u'timestamp': u'2007-08-04T22:34:59.000Z'},
             {u'creator': u'/user/awfrank',
              u'id': u'/m/0n8zp',
              u'lang': u'en',
              u'text': u'London Borough of Islington',
              u'timestamp': u'2007-08-04T22:33:26.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/0f485',
              u'lang': u'en',
              u'text': u'City of Westminster',
              u'timestamp': u'2007-08-03T17:37:27.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/0nlfr',
              u'lang': u'en',
              u'text': u'London Borough of Hammersmith and Fulham',
              u'timestamp': u'2007-08-03T17:37:03.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/021cv',
              u'lang': u'en',
              u'text': u'London Borough of Croydon',
              u'timestamp': u'2007-08-03T17:36:22.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0nccd',
              u'lang': u'en',
              u'text': u'London Borough of Enfield',
              u'timestamp': u'2007-07-02T07:57:44.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0nc96',
              u'lang': u'en',
              u'text': u'London Borough of Haringey',
              u'timestamp': u'2007-07-02T07:57:36.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0n9vx',
              u'lang': u'en',
              u'text': u'London Borough of Ealing',
              u'timestamp': u'2007-07-02T07:57:24.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0n9k4',
              u'lang': u'en',
              u'text': u'London Borough of Hounslow',
              u'timestamp': u'2007-07-02T07:57:14.000Z'}],
 u'valuetype': u'object'}
{u'count': 1.0,
 u'values': [{u'creator': u'/user/markh',
              u'id': u'/m/02hz1f6',
              u'lang': u'en',
              u'property': {u'/location/geocode/latitude': {u'count': 1.0,
                                                            u'values': [{u'creator': u'/user/geocode_bot',
                                                                         u'lang': u'en',
                                                                         u'text': u'51.507222',
                                                                         u'timestamp': u'2013-08-16T19:10:29.009Z',
                                                                         u'value': 51.507222}],
                                                            u'valuetype': u'float'},
                            u'/location/geocode/longitude': {u'count': 1.0,
                                                             u'values': [{u'creator': u'/user/geocode_bot',
                                                                          u'lang': u'en',
                                                                          u'text': u'-0.1275',
                                                                          u'timestamp': u'2013-08-06T11:08:50.000Z',
                                                                          u'value': -0.1275}],
                                                             u'valuetype': u'float'},
                            u'/type/object/attribution': {u'count': 1.0,
                                                          u'values': [{u'creator': u'/user/markh',
                                                                       u'id': u'/m/02hy_dv',
                                                                       u'lang': u'en',
                                                                       u'text': u'markh',
                                                                       u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                          u'valuetype': u'object'},
                            u'/type/object/type': {u'count': 1.0,
                                                   u'values': [{u'creator': u'/user/markh',
                                                                u'id': u'/location/geocode',
                                                                u'lang': u'en',
                                                                u'text': u'Geocode',
                                                                u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                   u'valuetype': u'object'}},
              u'text': u'51.507222 - -0.1275 - markh - Geocode',
              u'timestamp': u'2007-05-16T20:19:59.000Z'}],
 u'valuetype': u'compound'}
