Please input the city: {u'id': u'/m/04jpl',
 u'property': {u'/location/location/area': {u'count': 1.0,
                                            u'values': [{u'creator': u'/user/ellennor',
                                                         u'lang': u'en',
                                                         u'text': u'1572.0',
                                                         u'timestamp': u'2013-08-18T15:28:08.000Z',
                                                         u'value': 1572.0}],
                                            u'valuetype': u'float'},
               u'/location/location/containedby': {u'count': 3.0,
                                                   u'values': [{u'creator': u'/user/vlatsina',
                                                                u'id': u'/m/02jx1',
                                                                u'lang': u'en',
                                                                u'text': u'England',
                                                                u'timestamp': u'2012-11-07T11:07:01.000Z'},
                                                               {u'creator': u'/user/vlatsina',
                                                                u'id': u'/m/07ssc',
                                                                u'lang': u'en',
                                                                u'text': u'United Kingdom',
                                                                u'timestamp': u'2012-11-07T11:07:03.000Z'},
                                                               {u'creator': u'/user/jamie',
                                                                u'id': u'/m/034cm',
                                                                u'lang': u'en',
                                                                u'text': u'Great Britain',
                                                                u'timestamp': u'2013-04-18T21:16:31.000Z'}],
                                                   u'valuetype': u'object'},
               u'/location/location/contains': {u'count': 1553.0,
                                                u'values': [{u'creator': u'/user/kake',
                                                             u'id': u'/m/0nb9x',
                                                             u'lang': u'en',
                                                             u'text': u'Royal Borough of Kensington and Chelsea',
                                                             u'timestamp': u'2007-08-09T16:38:32.000Z'},
                                                            {u'creator': u'/user/awfrank',
                                                             u'id': u'/m/01d_0p',
                                                             u'lang': u'en',
                                                             u'text': u'Hyde Park',
                                                             u'timestamp': u'2007-08-04T22:34:59.000Z'},
                                                            {u'creator': u'/user/awfrank',
                                                             u'id': u'/m/0n8zp',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Islington',
                                                             u'timestamp': u'2007-08-04T22:33:26.000Z'},
                                                            {u'creator': u'/user/kake',
                                                             u'id': u'/m/0f485',
                                                             u'lang': u'en',
                                                             u'text': u'City of Westminster',
                                                             u'timestamp': u'2007-08-03T17:37:27.000Z'},
                                                            {u'creator': u'/user/kake',
                                                             u'id': u'/m/0nlfr',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Hammersmith and Fulham',
                                                             u'timestamp': u'2007-08-03T17:37:03.000Z'},
                                                            {u'creator': u'/user/kake',
                                                             u'id': u'/m/021cv',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Croydon',
                                                             u'timestamp': u'2007-08-03T17:36:22.000Z'},
                                                            {u'creator': u'/user/hex',
                                                             u'id': u'/m/0nccd',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Enfield',
                                                             u'timestamp': u'2007-07-02T07:57:44.000Z'},
                                                            {u'creator': u'/user/hex',
                                                             u'id': u'/m/0nc96',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Haringey',
                                                             u'timestamp': u'2007-07-02T07:57:36.000Z'},
                                                            {u'creator': u'/user/hex',
                                                             u'id': u'/m/0n9vx',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Ealing',
                                                             u'timestamp': u'2007-07-02T07:57:24.000Z'},
                                                            {u'creator': u'/user/hex',
                                                             u'id': u'/m/0n9k4',
                                                             u'lang': u'en',
                                                             u'text': u'London Borough of Hounslow',
                                                             u'timestamp': u'2007-07-02T07:57:14.000Z'}],
                                                u'valuetype': u'object'},
               u'/location/location/events': {u'count': 441.0,
                                              u'values': [{u'creator': u'/user/eiahdelacruz',
                                                           u'id': u'/m/04mw8p5',
                                                           u'lang': u'en',
                                                           u'text': u'2008 Raindance Film Festival',
                                                           u'timestamp': u'2008-10-16T13:40:37.000Z'},
                                                          {u'creator': u'/user/sprocketonline',
                                                           u'id': u'/m/04zjnvq',
                                                           u'lang': u'en',
                                                           u'text': u'Ocean transport and erection of Cleopatra\u2019s Needle, (from Egypt to) London, 1878',
                                                           u'timestamp': u'2008-12-01T07:35:53.000Z'},
                                                          {u'creator': u'/user/tordans',
                                                           u'id': u'/m/0q8by',
                                                           u'lang': u'en',
                                                           u'text': u'World Organization of the Scout Movement',
                                                           u'timestamp': u'2009-02-01T13:36:40.000Z'},
                                                          {u'creator': u'/user/spencermountain',
                                                           u'id': u'/m/01smld',
                                                           u'lang': u'en',
                                                           u'text': u'2003 London blackout',
                                                           u'timestamp': u'2009-02-12T22:50:40.003Z'},
                                                          {u'creator': u'/user/reaj',
                                                           u'id': u'/m/02phxdp',
                                                           u'lang': u'en',
                                                           u'text': u'Live Earth',
                                                           u'timestamp': u'2009-02-17T22:16:56.000Z'},
                                                          {u'creator': u'/user/mgutierrezt',
                                                           u'id': u'/m/098xl9',
                                                           u'lang': u'en',
                                                           u'text': u'Grunwick dispute',
                                                           u'timestamp': u'2009-02-26T19:48:24.000Z'},
                                                          {u'creator': u'/user/camillejoyceloza',
                                                           u'id': u'/m/09bb_y',
                                                           u'lang': u'en',
                                                           u'text': u'Early fires of London',
                                                           u'timestamp': u'2009-02-28T07:14:51.000Z'},
                                                          {u'creator': u'/user/camillejoyceloza',
                                                           u'id': u'/m/09_t2q',
                                                           u'lang': u'en',
                                                           u'text': u'Fathers 4 Justice protests',
                                                           u'timestamp': u'2009-03-05T17:26:23.000Z'},
                                                          {u'creator': u'/user/sanxiyn',
                                                           u'id': u'/m/0cs6qq',
                                                           u'lang': u'en',
                                                           u'text': u'1st Computer Olympiad',
                                                           u'timestamp': u'2009-03-10T08:24:01.000Z'},
                                                          {u'creator': u'/user/sanxiyn',
                                                           u'id': u'/m/0cs6gs',
                                                           u'lang': u'en',
                                                           u'text': u'2nd Computer Olympiad',
                                                           u'timestamp': u'2009-03-10T08:50:26.000Z'}],
                                              u'valuetype': u'object'},
               u'/location/location/geolocation': {u'count': 1.0,
                                                   u'values': [{u'creator': u'/user/markh',
                                                                u'id': u'/m/02hz1f6',
                                                                u'lang': u'en',
                                                                u'property': {u'/location/geocode/latitude': {u'count': 1.0,
                                                                                                              u'values': [{u'creator': u'/user/geocode_bot',
                                                                                                                           u'lang': u'en',
                                                                                                                           u'text': u'51.507222',
                                                                                                                           u'timestamp': u'2013-08-16T19:10:29.009Z',
                                                                                                                           u'value': 51.507222}],
                                                                                                              u'valuetype': u'float'},
                                                                              u'/location/geocode/longitude': {u'count': 1.0,
                                                                                                               u'values': [{u'creator': u'/user/geocode_bot',
                                                                                                                            u'lang': u'en',
                                                                                                                            u'text': u'-0.1275',
                                                                                                                            u'timestamp': u'2013-08-06T11:08:50.000Z',
                                                                                                                            u'value': -0.1275}],
                                                                                                               u'valuetype': u'float'},
                                                                              u'/type/object/attribution': {u'count': 1.0,
                                                                                                            u'values': [{u'creator': u'/user/markh',
                                                                                                                         u'id': u'/m/02hy_dv',
                                                                                                                         u'lang': u'en',
                                                                                                                         u'text': u'markh',
                                                                                                                         u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                                                                            u'valuetype': u'object'},
                                                                              u'/type/object/type': {u'count': 1.0,
                                                                                                     u'values': [{u'creator': u'/user/markh',
                                                                                                                  u'id': u'/location/geocode',
                                                                                                                  u'lang': u'en',
                                                                                                                  u'text': u'Geocode',
                                                                                                                  u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                                                                     u'valuetype': u'object'}},
                                                                u'text': u'51.507222 - -0.1275 - markh - Geocode',
                                                                u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                   u'valuetype': u'compound'},
               u'/location/location/nearby_airports': {u'count': 9.0,
                                                       u'values': [{u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/01dcgl',
                                                                    u'lang': u'en',
                                                                    u'text': u'Luton Airport',
                                                                    u'timestamp': u'2007-03-30T02:21:50.002Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/01jrrf',
                                                                    u'lang': u'en',
                                                                    u'text': u'London City Airport',
                                                                    u'timestamp': u'2007-03-30T02:21:59.000Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/0hcsh',
                                                                    u'lang': u'en',
                                                                    u'text': u'London Stansted Airport',
                                                                    u'timestamp': u'2007-03-30T02:22:04.004Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/03jn4',
                                                                    u'lang': u'en',
                                                                    u'text': u'London Heathrow Airport',
                                                                    u'timestamp': u'2007-03-30T02:22:17.010Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/0pr6s',
                                                                    u'lang': u'en',
                                                                    u'text': u'Gatwick Airport',
                                                                    u'timestamp': u'2007-03-30T02:22:55.006Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/0349jm',
                                                                    u'lang': u'en',
                                                                    u'text': u'London Heliport',
                                                                    u'timestamp': u'2007-03-30T02:23:41.006Z'},
                                                                   {u'creator': u'/user/mwcl_infobox',
                                                                    u'id': u'/m/021ycc',
                                                                    u'lang': u'en',
                                                                    u'text': u'London Biggin Hill Airport',
                                                                    u'timestamp': u'2007-03-30T02:23:54.001Z'},
                                                                   {u'creator': u'/user/mw_template_bot',
                                                                    u'id': u'/m/0fzxv_',
                                                                    u'lang': u'en',
                                                                    u'text': u'Lydd Airport',
                                                                    u'timestamp': u'2008-02-10T18:52:45.002Z'},
                                                                   {u'creator': u'/user/mw_template_bot',
                                                                    u'id': u'/m/0pqw1',
                                                                    u'lang': u'en',
                                                                    u'text': u'Croydon Airport',
                                                                    u'timestamp': u'2009-12-19T18:58:53.001Z'}],
                                                       u'valuetype': u'object'},
               u'/location/location/partially_contains': {u'count': 2.0,
                                                          u'values': [{u'creator': u'/user/stsvetanova',
                                                                       u'id': u'/m/01_grn',
                                                                       u'lang': u'en',
                                                                       u'text': u'River Lea',
                                                                       u'timestamp': u'2013-07-27T12:44:05.000Z'},
                                                                      {u'creator': u'/user/regiepl',
                                                                       u'id': u'/m/0d2kt',
                                                                       u'lang': u'en',
                                                                       u'text': u'River Thames',
                                                                       u'timestamp': u'2013-07-27T16:26:44.000Z'}],
                                                          u'valuetype': u'object'},
               u'/location/location/partiallycontains': {u'count': 2.0,
                                                         u'values': [{u'creator': u'/user/schema_bot',
                                                                      u'id': u'/m/0wg9mld',
                                                                      u'lang': u'en',
                                                                      u'property': {u'/location/partial_containment_relationship/partially_contains': {u'count': 1.0,
                                                                                                                                                       u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                                                                    u'id': u'/m/01_grn',
                                                                                                                                                                    u'lang': u'en',
                                                                                                                                                                    u'text': u'River Lea',
                                                                                                                                                                    u'timestamp': u'2013-08-05T21:58:58.000Z'}],
                                                                                                                                                       u'valuetype': u'object'},
                                                                                    u'/type/object/attribution': {u'count': 1.0,
                                                                                                                  u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                               u'id': u'/m/0n_b8yc',
                                                                                                                               u'lang': u'en',
                                                                                                                               u'text': u'schema_bot',
                                                                                                                               u'timestamp': u'2013-08-05T21:58:58.000Z'}],
                                                                                                                  u'valuetype': u'object'},
                                                                                    u'/type/object/type': {u'count': 1.0,
                                                                                                           u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                        u'id': u'/location/partial_containment_relationship',
                                                                                                                        u'lang': u'en',
                                                                                                                        u'text': u'Partial containment relationship',
                                                                                                                        u'timestamp': u'2013-08-05T21:58:58.000Z'}],
                                                                                                           u'valuetype': u'object'}},
                                                                      u'text': u'River Lea - schema_bot - Partial containment relationship',
                                                                      u'timestamp': u'2013-08-05T21:58:58.000Z'},
                                                                     {u'creator': u'/user/schema_bot',
                                                                      u'id': u'/m/0wg9mlk',
                                                                      u'lang': u'en',
                                                                      u'property': {u'/location/partial_containment_relationship/partially_contains': {u'count': 1.0,
                                                                                                                                                       u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                                                                    u'id': u'/m/0d2kt',
                                                                                                                                                                    u'lang': u'en',
                                                                                                                                                                    u'text': u'River Thames',
                                                                                                                                                                    u'timestamp': u'2013-08-05T21:58:59.000Z'}],
                                                                                                                                                       u'valuetype': u'object'},
                                                                                    u'/type/object/attribution': {u'count': 1.0,
                                                                                                                  u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                               u'id': u'/m/0n_b8yc',
                                                                                                                               u'lang': u'en',
                                                                                                                               u'text': u'schema_bot',
                                                                                                                               u'timestamp': u'2013-08-05T21:58:59.000Z'}],
                                                                                                                  u'valuetype': u'object'},
                                                                                    u'/type/object/type': {u'count': 1.0,
                                                                                                           u'values': [{u'creator': u'/user/schema_bot',
                                                                                                                        u'id': u'/location/partial_containment_relationship',
                                                                                                                        u'lang': u'en',
                                                                                                                        u'text': u'Partial containment relationship',
                                                                                                                        u'timestamp': u'2013-08-05T21:58:59.000Z'}],
                                                                                                           u'valuetype': u'object'}},
                                                                      u'text': u'River Thames - schema_bot - Partial containment relationship',
                                                                      u'timestamp': u'2013-08-05T21:58:59.000Z'}],
                                                         u'valuetype': u'compound'},
               u'/location/location/people_born_here': {u'count': 10864.0,
                                                        u'values': [{u'creator': u'/user/kurt',
                                                                     u'id': u'/m/09vlqr',
                                                                     u'lang': u'en',
                                                                     u'text': u'Toby Froud',
                                                                     u'timestamp': u'2006-12-18T06:38:11.000Z'},
                                                                    {u'creator': u'/user/patrick',
                                                                     u'id': u'/m/01blg8',
                                                                     u'lang': u'en',
                                                                     u'text': u'Beau Brummell',
                                                                     u'timestamp': u'2007-02-28T17:49:51.000Z'},
                                                                    {u'creator': u'/user/bijna',
                                                                     u'id': u'/m/022q46_',
                                                                     u'lang': u'en',
                                                                     u'text': u'Alexander Marks',
                                                                     u'timestamp': u'2007-03-20T19:45:31.000Z'},
                                                                    {u'creator': u'/user/patrick',
                                                                     u'id': u'/m/0505__',
                                                                     u'lang': u'en',
                                                                     u'text': u'Sir Lewis Leigh Fermor',
                                                                     u'timestamp': u'2007-04-23T20:57:01.000Z'},
                                                                    {u'creator': u'/user/bquinn',
                                                                     u'id': u'/m/031g8l',
                                                                     u'lang': u'en',
                                                                     u'text': u'Mark Thompson',
                                                                     u'timestamp': u'2007-05-03T07:29:12.000Z'},
                                                                    {u'creator': u'/user/markhopwood',
                                                                     u'id': u'/m/02hqnp3',
                                                                     u'lang': u'en',
                                                                     u'text': u'Mark Hopwood',
                                                                     u'timestamp': u'2007-05-08T15:38:09.000Z'},
                                                                    {u'creator': u'/user/stevec',
                                                                     u'id': u'/m/0dszs',
                                                                     u'lang': u'en',
                                                                     u'text': u'Stephen Wolfram',
                                                                     u'timestamp': u'2007-05-12T21:15:40.000Z'},
                                                                    {u'creator': u'/user/crism',
                                                                     u'id': u'/m/028tyf',
                                                                     u'lang': u'en',
                                                                     u'text': u'Dee Palmer',
                                                                     u'timestamp': u'2007-05-14T12:43:33.000Z'},
                                                                    {u'creator': u'/user/hilary',
                                                                     u'id': u'/m/0bqyq3',
                                                                     u'lang': u'en',
                                                                     u'text': u'Cecily Brown',
                                                                     u'timestamp': u'2007-05-17T04:44:25.000Z'},
                                                                    {u'creator': u'/user/jaronoff',
                                                                     u'id': u'/m/04x56',
                                                                     u'lang': u'en',
                                                                     u'text': u'Michael Moorcock',
                                                                     u'timestamp': u'2007-05-19T20:46:29.000Z'}],
                                                        u'valuetype': u'object'},
               u'/location/location/time_zones': {u'count': 1.0,
                                                  u'values': [{u'creator': u'/user/mw_template_bot',
                                                               u'id': u'/m/03bdv',
                                                               u'lang': u'en',
                                                               u'text': u'Greenwich Mean Time Zone',
                                                               u'timestamp': u'2008-10-09T00:31:12.000Z'}],
                                                  u'valuetype': u'object'}}}
{u'count': 1553.0,
 u'values': [{u'creator': u'/user/kake',
              u'id': u'/m/0nb9x',
              u'lang': u'en',
              u'text': u'Royal Borough of Kensington and Chelsea',
              u'timestamp': u'2007-08-09T16:38:32.000Z'},
             {u'creator': u'/user/awfrank',
              u'id': u'/m/01d_0p',
              u'lang': u'en',
              u'text': u'Hyde Park',
              u'timestamp': u'2007-08-04T22:34:59.000Z'},
             {u'creator': u'/user/awfrank',
              u'id': u'/m/0n8zp',
              u'lang': u'en',
              u'text': u'London Borough of Islington',
              u'timestamp': u'2007-08-04T22:33:26.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/0f485',
              u'lang': u'en',
              u'text': u'City of Westminster',
              u'timestamp': u'2007-08-03T17:37:27.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/0nlfr',
              u'lang': u'en',
              u'text': u'London Borough of Hammersmith and Fulham',
              u'timestamp': u'2007-08-03T17:37:03.000Z'},
             {u'creator': u'/user/kake',
              u'id': u'/m/021cv',
              u'lang': u'en',
              u'text': u'London Borough of Croydon',
              u'timestamp': u'2007-08-03T17:36:22.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0nccd',
              u'lang': u'en',
              u'text': u'London Borough of Enfield',
              u'timestamp': u'2007-07-02T07:57:44.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0nc96',
              u'lang': u'en',
              u'text': u'London Borough of Haringey',
              u'timestamp': u'2007-07-02T07:57:36.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0n9vx',
              u'lang': u'en',
              u'text': u'London Borough of Ealing',
              u'timestamp': u'2007-07-02T07:57:24.000Z'},
             {u'creator': u'/user/hex',
              u'id': u'/m/0n9k4',
              u'lang': u'en',
              u'text': u'London Borough of Hounslow',
              u'timestamp': u'2007-07-02T07:57:14.000Z'}],
 u'valuetype': u'object'}
{u'count': 1.0,
 u'values': [{u'creator': u'/user/markh',
              u'id': u'/m/02hz1f6',
              u'lang': u'en',
              u'property': {u'/location/geocode/latitude': {u'count': 1.0,
                                                            u'values': [{u'creator': u'/user/geocode_bot',
                                                                         u'lang': u'en',
                                                                         u'text': u'51.507222',
                                                                         u'timestamp': u'2013-08-16T19:10:29.009Z',
                                                                         u'value': 51.507222}],
                                                            u'valuetype': u'float'},
                            u'/location/geocode/longitude': {u'count': 1.0,
                                                             u'values': [{u'creator': u'/user/geocode_bot',
                                                                          u'lang': u'en',
                                                                          u'text': u'-0.1275',
                                                                          u'timestamp': u'2013-08-06T11:08:50.000Z',
                                                                          u'value': -0.1275}],
                                                             u'valuetype': u'float'},
                            u'/type/object/attribution': {u'count': 1.0,
                                                          u'values': [{u'creator': u'/user/markh',
                                                                       u'id': u'/m/02hy_dv',
                                                                       u'lang': u'en',
                                                                       u'text': u'markh',
                                                                       u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                          u'valuetype': u'object'},
                            u'/type/object/type': {u'count': 1.0,
                                                   u'values': [{u'creator': u'/user/markh',
                                                                u'id': u'/location/geocode',
                                                                u'lang': u'en',
                                                                u'text': u'Geocode',
                                                                u'timestamp': u'2007-05-16T20:19:59.000Z'}],
                                                   u'valuetype': u'object'}},
              u'text': u'51.507222 - -0.1275 - markh - Geocode',
              u'timestamp': u'2007-05-16T20:19:59.000Z'}],
 u'valuetype': u'compound'}
